apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pdf-gen
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  replicas:
    min: 1
    max: 4
    cpuThresholdPercentage: 70
  liveness:
    path: /is_alive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_alive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  leaderElection: false
  prometheus:
    enabled: true
    path: /prometheus
  istio:
    enabled: false
  resources:
    limits:
      cpu: 2000m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 512Mi
  ingress:
    disabled: false
