name: Build-Deploy
on:
  push:
    branches:
      - main
env:
  NEW_VERSION: ${{ github.event.release.tag_name }}

permissions:
  contents: write
  pull-requests: write
  packages: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1
      - name: Setup gradle dependency cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/.*gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        run: ./gradlew -Pversion=${{ env.NEW_VERSION }} build
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: java
          package-name: pdfgen-core
          include-v-in-tag: false
      - name: Upload to github packages
        if: ${{ steps.release.outputs.release_created }}
        run: ./gradlew -Pversion=${{ env.NEW_VERSION }} publish
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}